image: python:3.12 # Use the Python version that matches your development environment

pipelines:
  branches:
    main:
      - step:
          script:
            - python3 -m venv venv # Create a virtual environment
            - source venv/bin/activate # Activate the virtual environment
            # - pip install --upgrade pip
            # - pip install -r requirements.txt # Install dependencies
            # - pytest # Run tests
