# Generated by Django 4.1.13 on 2024-04-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('vehicle_id', models.CharField(max_length=30, null=True)),
                ('vehicle_type', models.CharField(max_length=30, null=True)),
                ('initial_destination', models.CharField(max_length=64, null=True)),
                ('initial_destination_latitude', models.FloatField(null=True)),
                ('initial_destination_longitude', models.FloatField(null=True)),
                ('final_destination', models.CharField(max_length=64, null=True)),
                ('route', models.TextField(null=True)),
                ('pickup_waypoint', models.TextField(null=True)),
                ('dropoff_waypoint', models.TextField(null=True)),
                ('vehicle_location', models.TextField(null=True)),
                ('order_id', models.CharField(max_length=256, null=True)),
                ('trip_percentage', models.FloatField(default=0.0)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
