# Generated by Django 4.1.13 on 2024-04-29 01:24

from django.db import migrations, models
import django.db.models.deletion
import plugin_skeleton.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address_manager', '0002_address_hashed_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('username', models.CharField(default='', max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPING', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled'), ('NOT_PLACED', 'Not_placed')], default='NOT_PLACED', max_length=50)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('trip_id', models.IntegerField(null=True)),
                ('order_id', plugin_skeleton.models.AutoIncrementCharField(max_length=255, primary_key=True, serialize=False)),
                ('dropoff_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_pickup_address', related_query_name='%(app_label)s_%(class)s_pickup_orders', to='address_manager.address')),
                ('pickup_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_dropoff_address', related_query_name='%(app_label)s_%(class)s_dropoff_orders', to='address_manager.address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifetime_drones.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifetime_drones.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
