# Generated by Django 4.1.13 on 2024-04-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
